name: Test Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Compile LaTeX
      uses: xu-cheng/latex-action@master
      with:
        root_file: subcommittee_regulations.tex
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: pdf
        path: subcommittee_regulations.pdf
    - uses: actions/upload-artifact@v1
      if: always()
      with:
        name: log
        path: subcommittee_regulations.log
